### ISSUE TITLE
Linux VST2: undefined references for __cpu_model, __cpu_indicator_init

### ISSUE THREAD

**Issue by whydoubt** [kurasu/surge#130] opened 2018-12-20 22:33 UTC
As a quick-n-dirty check for undefined references on Linux, I run
```
ld -o /dev/null target/vst2/Debug/Surge-Debug.so
```

I get `__cpu_model` and `__cpu_indicator_init` reported as undefined.  I found that it seems to be related to the use of `__builtin_cpu_supports`.  It can be fixed in one of two ways: link with gcc instead of g++, or add libgcc and libgcc_s to the libraries to link.

I wondered if anyone else had seen this?

This is on current master (5e6a7351) with no changes to it or vst3sdk,
```
rm -rf *.make Makefile obj target
VST2SDK_DIR=... premake5 gmake
make surge-vst2
```
It applies to the release version as well.
I read that this was supposed to be fixed in gcc 6, but I am using gcc/g++ version 7.3.1 on fedora 27.

#19

**Comment by baconpaul** [comment] 2018-12-20 23:59
That ld trick is cute. I always used a version of nm -g and grep and un-doing the name mangle in my head.

Anyway I can't build VST2 but I can build VST3 and then I get __cpu_mode and moduleHandle being undefined as well as all the stuff in SurgeVst3EditController which didn't build on mac.

**Comment by baconpaul** [comment] 2018-12-21 00:34
Apologies for screenshots. My VM isn't copy and pasting to my browser properly.

With these three diffs

First stub out SurgeVST3EditController just like I did on mac (two diffs)

<img width="856" alt="screen shot 2018-12-20 at 7 30 42 pm" src="https://user-images.githubusercontent.com/13387561/50318228-d90e3e80-048d-11e9-9734-22fbf6a18fca.png">

Second add -lgcc_s and -lgcc to premake5.lua

<img width="633" alt="screen shot 2018-12-20 at 7 32 03 pm" src="https://user-images.githubusercontent.com/13387561/50318263-0824b000-048e-11e9-98dd-732263a62ac0.png">

your LD trick shows me 


<img width="896" alt="screen shot 2018-12-20 at 7 33 04 pm" src="https://user-images.githubusercontent.com/13387561/50318277-2094ca80-048e-11e9-9daf-ac827b7eb8f2.png">

Without the premake change I also see __cpu_blah and without the ifdef a bunch of SurgeVST3Blah

Can you try with those diffs?

**Comment by whydoubt** [comment] 2018-12-21 01:02
I actually have several patches prepared for all of these. Just checking if others were getting them.  Note: I have submitted a fix for the missing getTicks64 reference to Steinberg: https://github.com/steinbergmedia/vst3_base/pull/1

**Comment by baconpaul** [comment] 2018-12-21 01:04
Oh OK cool I'll stop hacking on them then. You added linuxmain to the vst3 files for linux too? That got rid of moduleHandle.

Is there something to do about getTicks64 while we wait for steinberg? Could we include a patch file that we apply for instance?

**Comment by whydoubt** [comment] 2018-12-21 15:40
I wasn't using linuxmain before, but I will be now.  It looks like it will solve a couple of other things I was doing another way.

**Comment by baconpaul** [comment] 2018-12-21 16:06
Hey cool! Feels like we are closing in on a working VST3 on Linux! Nice.

**Comment by baconpaul** [comment] 2018-12-21 18:22
Hmm ... sounds tricky. Do you have those patches in a way which we could non intrusively merge so other people can look? But I’m sympathetic - I went through a few tries before I got Mac au to a point where I was even willing to think about a pr!

Also curious how the ui code is different.

**Comment by jsakkine** [comment] 2018-12-22 05:33
This issue must have been caused by me with the changes to `CpuArchitecture.cpp`. Checked but I don't see `cpu_*` to be undefined. My GCC version is `gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0`.

**Comment by jsakkine** [comment] 2018-12-22 05:36
@baconpaul I'd just SSH to the VM.

**Comment by jsakkine** [comment] 2018-12-22 05:39
BTW, what is the function of `vst2wrapper.cpp` and `vst2wrapper.sdk.cpp`?

**Comment by jsakkine** [comment] 2018-12-22 07:05
I looked into another open source synth called Tunefish. Their evolution with the UI was

1. VSTGUI
2. Qt 
3. JUCE

Would be interesting the know for long-term plans what were the core reasons to eventually migrate to JUCE and is that something that we should consider in long-term. With my VSTGUI experience I can't really tell...

**Comment by asimilon** [comment] 2018-12-22 12:20
I just forked that yesterday to add in some newer hosts in their host detection code, as we are using it in my day job and so for the people signed up to analytics it's good for us to know about the newer hosts :)
I like JUCE as it's what I started off with for audio plugin dev.  If there is a specific reason to migrate (something JUCE can do that VSTGUI doesn't) then I can see the value, otherwise it feels a bit like "if it ain't broke, don't need to fix" :)  tbh though I haven't really been looking at any of the code, my involvement in this project has just been in the build and package process so far, and that was all I was really interested in, as I used it before, but since upgrading to Cubase 9.5 which doesn't support 32bit plugins without a bridge I was SooL.  Having said that I haven't really had a chance to play with it beyond testing that it loads and produces some sound, so I don't know if there are any problems that need addressing.

**Comment by jsakkine** [comment] 2018-12-22 12:36
Emailed. Hope we get some feedback :)

**Comment by baconpaul** [comment] 2018-12-22 12:49
I think the practical reason for why this isn’t a JUCE application has, at least in part, the fact that it was version 1.0 in 2005. I agree that JUCE could make a lot of our wrangling easier - it’s a pretty good bit of kit with a great license for open source projects - and could also save us pain on things like an AUv3 port in the future.

But  I also completely agree: We should get what we have working and maybe call it a version “1.7 open source” or some such and then do some sort of re-plan pow wow. If you ask me, that 1.7 should be close to current surge with bugs fixed and compatible formats on all three OSes. Maybe not 32 bit but definitely one or both VST and AU.

**Comment by jsakkine** [comment] 2018-12-22 15:18
@baconpaul, fully agree.

**Comment by whydoubt** [comment] 2018-12-23 06:43
Having poked at both Surge and VSTGUI on Linux for a bit now, I feel that VSTGUI on Linux is rather unstable.  Some things are getting fixed, while others get broken.  It's no wonder I wasn't finding other Linux VST plugins using VSTGUI.

**Comment by jsakkine** [comment] 2018-12-23 12:34
My wild guess is that is the conclusion that they ended up with Tunefish.

**Comment by baconpaul** [comment] 2018-12-23 12:52
Rewriting the ui and build deploy process in juce is “a lot of work” though. Is that work which you conclude is needed? Or is there some other idea of what to do?

Also what’s needed to run it and see the bugs? Currrmt master isn’t even that far is it?

Thanks!

**Comment by jsakkine** [comment] 2018-12-23 12:55
We could target 1.7 release DoD that it works for macOS and Windows. I do agree that it would be grazy to do any type of switch right now. Still waiting response from Tunefish devs. That is worth looking through. But yeah, that is what I think would be sane way to manage this project further with the current knowledge.

**Comment by jsakkine** [comment] 2018-12-23 13:01
If we ignore the GUI, most of the time fixing something for macOS, will fix it also for any *nix.

**Comment by baconpaul** [comment] 2019-01-03 08:07
@whydoubt lots of folks in #19 reporting that Linux links so i think this particular symbol issue is resolved. So I’m going to close this ticket.

**Closed by baconpaul** 2019-01-03 08:07 UTC
