### ISSUE TITLE
Doesn't compile on xcode 9.4.1

### ISSUE THREAD

**Issue by JurekR** [kurasu/surge#3] opened 2018-09-22 15:13 UTC
Hi,

I was not able to compile the VST3 version using High Sierra and XCode 9.4.1 so far, since I ran into multiple issues. Surely it is because I have no idea what I am doing :)

- Patched build-osx.sh to use premake5 instead premake4
- Some strange header include errors, fixed by using "always search user paths"
- Then libc++ problems with the math calls, "filesystem" not found.Adding header path "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/" did not work

**Comment by JurekR** [comment] 2018-09-25 22:57
SurgeStorage.h:20:10: 'filesystem' file not found
it is not part of libc++ in xcode 9, cannot find it under "experimental/" either.
https://stackoverflow.com/questions/42633477/macos-clang-c17-filesystem-header-not-found
Seems that it will work with xcode 10, using experimental/filesystem.... Will do a system update soon.

**Comment by JurekR** [comment] 2018-09-26 07:59
No change with xcode 10 on 10.13.6.

**Comment by asimilon** [comment] 2018-09-26 18:18
using `homebrew install llvm` and some of the instructions [here](http://antonmenshov.com/2017/09/09/clang-openmp-setup-in-xcode/), I've managed to get beyond `<filesystem>` not being available to Xcode 9.2 (I'm trying to build on Sierra)
But got stuck with some `Cannot initialize a parameter of type 'wchar_t *' with an lvalue of type 'Steinberg::Vst::String128' (aka 'Steinberg::Vst::TChar [128]')` errors instead in calls such as `SurgeSynthesizer::getParameterNameW`.

**Comment by kurasu** [comment] 2018-09-26 19:01
I think you could safely change these method to take a char* instead of a wchar_t* as it only assembles chars anyway in these 4 methods. (and then use swprintf and so on)

Longer term a better strategy would be good how to deal with strings at these layers in a nicer way, but for just getting mac building i'm happy with changing this.

**Comment by asimilon** [comment] 2018-09-26 20:14
OK, so that didn't help, and it also made VST2 start complaining about those methods, **but** leaving those as is I've succesfully built VST2 now!

**Comment by kzantow** [comment] 2018-09-27 05:13
@kurasu any issue just changing usage of `<filesystem>`, which seems to be just `fs::path` to `string`?

**Comment by asimilon** [comment] 2018-09-27 06:31
fs::directory_iterator is used too, there may be more

**Comment by kurasu** [comment] 2018-09-27 07:49
yeah, i was moving over to using filesystem in order to make linux porting easier no that its finally moving into the c++ spec, but it seems macOS is lagging here. But using the experimental namespace should be ok with homebrew llvm, right?

**Comment by asimilon** [comment] 2018-09-27 07:53
I had to remove the experimental portion of the namespace for it to build.
I pushed a separate branch on my fork so that others can build if they wish
but will look into how I can get it to work with premake before issuing a
pull request.

**Comment by esaruoho** [comment] 2018-11-24 18:18
> using `homebrew install llvm` 

you wanna do `brew install llvm` instead? i pasted in your string and immediately got a "homebrew command not found" error ;)

**Comment by JurekR** [comment] 2018-11-24 19:16
Download and install it manually from premake webpage, there is a binary package.

**Comment by esaruoho** [comment] 2018-11-24 19:30
the three "build failed" errors, btw were:

```
error: Build input file cannot be found:
'surge/vst3sdk/vstgui4/vstgui/vstgui_mac.mm'

** BUILD FAILED **

error: Build input file cannot be found:
'surge/vst3sdk/public.sdk/source/vst/vstsinglecomponenteffect.cpp'

** BUILD FAILED **

error: Build input file cannot be found:
'surge/vst3sdk/vstgui4/vstgui/vstgui_uidescription_mac.mm'

** BUILD FAILED **
```

is there a way of including these directly in the surge repo so that the files are fully there?

**Comment by JurekR** [comment] 2018-11-24 20:14
Did you do a "git submodule update --init --recursive" as stated in the readme? It should download the missing VST SDKs. Though I only tried to build the VST2 version so far, and kurasu seems to be pretty busy with upcoming Bitwig version now.

**Comment by esaruoho** [comment] 2018-11-24 20:34
> AU complains about missing `plugin.h`.

yep, same issue here. not sure how to solve it, since i don't know what plugin.h should be, or what it should contain? logged this issue at #34

**Comment by esaruoho** [comment] 2018-12-04 08:00
@JurekR are you still working on making this compile?

**Comment by kzantow** [comment] 2018-12-08 15:30
@esaruoho I'm using xcode 10 and have the same problem -- got it compiling (submitted a patch), but it doesn't show up in any DAW. I am too much of a C++/VST/etc. noob to know exactly what the issue is, but I assume it's something to do with either a) files not being included in the contents of the `.vst` or b) not correctly building a shared library. I'll try to experiment a bit today and see if I can figure out the issue on my platform, probably the same as xcode 9...

**Comment by kzantow** [comment] 2018-12-08 15:58
I think I may have figured this last bit out but now running into a build issue getting VST2 built. *sigh*

**Comment by kzantow** [comment] 2018-12-08 17:02
I found a few things so far, but I figured out how to get plugin loading messages out of Bitwig, and it says:
```
2018-12-08 11:59:03.552 BitwigPluginHost[14732:14822587] Error loading /Library/Audio/Plug-Ins/VST/Surge.vst/Contents/MacOS/Surge:  dlopen(/Library/Audio/Plug-Ins/VST/Surge.vst/Contents/MacOS/Surge, 262): no suitable image found.  Did find:
	/Library/Audio/Plug-Ins/VST/Surge.vst/Contents/MacOS/Surge: mach-o, but wrong architecture
```
... getting closer, and at least I have a way to know what's going on during loading (at least in one host).

**Comment by kzantow** [comment] 2018-12-08 17:38
I tried explicitly building `x86_64`, verified the dylib was correct:
```
$ lipo -info target/vst2/Release/Surge.dylib
Non-fat file: target/vst2/Release/Surge.dylib is architecture: x86_64
```
Verified the host had the same architecture (Bitwig has both 64 and 32 bit host processes):
```
$ lipo -info /Applications/Bitwig\ Studio.app/Contents/MacOS/Bitwig\ Plug-in\ Host\ 64.app/Contents/MacOS/BitwigPluginHost 
Non-fat file: /Applications/Bitwig Studio.app/Contents/MacOS/Bitwig Plug-in Host 64.app/Contents/MacOS/BitwigPluginHost is architecture: x86_64
```
... so I'm at a bit of a loss what to do now, any ideas?

**Comment by esaruoho** [comment] 2018-12-08 20:20
@kzantow awesome! renoise and ableton live just don't recognize it at all, so it's good that bitwig gives some sort of data :) thanks for checking it out!

**Comment by kzantow** [comment] 2018-12-09 17:47
I know very little about assembly programming and how it affects binaries, could it be that some of the `__asm` blocks targeting `MAC` are changing the architecture somehow?

**Comment by esaruoho** [comment] 2018-12-14 21:05
@kzantow are you able to use http://github.com/tracktion/pluginval to be able to get some more validation out of the VST2/VST3? :)

**Comment by esaruoho** [comment] 2018-12-18 16:25
@jurekr how are things post #92 PR getting merged in? Still the same issue?

**Comment by baconpaul** [comment] 2018-12-19 22:05
So with all the PRs in the last week, multiple people have built on Xcode 9.4.1 10 and 9.2 all, fixing many of the errors which went by in this thread. So I’m going to close this issue. @JurekR if you pull to the top of master and follow the new README instructions you should get a good build. If not please let us know!

**Closed by baconpaul** 2018-12-19 22:05 UTC
Labels: help wanted

**Comment by esaruoho** [comment] 2019-01-18 12:45
@JurekR were you looking to build a 32-bit macOS VST2,VST3,AU or 64-bit? If you were interested in trying to make it compile 32-bit versions, please join the conversation at #115 if you have something interesting to add.
