### ISSUE TITLE
Win32 build possible, but has bugs

### ISSUE THREAD

**Issue by getdunne** [kurasu/surge#14] opened 2018-09-26 18:58 UTC
I was able to build the VST2 for Win32/x86 in VS2017, but it exhibits glitches with some presets, most notably "Polysynth - FM Poly 1".

1. Use VS2017 Configuration Manager to add the Win32 platform, then build the 32-bit VST2.
2. Open 32-bit VST2 in a 32-bit VST host (I used Hermann Seib's VSTHost).
3. Select preset "Polysynth - Embrass" and play lots of notes
4. Select preset "Polysynth - FM Poly 1" and play just two notes legato - second one will glitch.

This does NOT happen with the 64-bit build. There may be an underlying bug which mainly manifests in the 32-bit version for some reason.

**Comment by synthtester** [comment] 2018-09-27 23:35
Can you share it? I'm here after following link from Vember that says binaries are available but the only Windows installer I found is x64.

**Comment by getdunne** [comment] 2018-09-28 01:12
> Can you share it? I'm here after following link from Vember that says binaries are available but the only Windows installer I found is x64.

@kurasu can you share this? If I do it, it will violate my license from Steinberg; I'm not prepared to risk that.

**Comment by esaruoho** [comment] 2018-12-08 20:16
@getdunne hold on, what? Is this because of Steinberg's VST2 license or something, or why can't a regular VST be made available for free without running into Steinberg issues? can ya somehow explain this further?

**Comment by esaruoho** [comment] 2018-12-18 09:39
@getdunne is there any chance you could document the VS2017 - settings and building further so someone could make a PR / Branch out of that and maybe update the `README.md` file so we'll eventually be able to bake VSTs. This way nobody needs to create a `.dll` with their own VST license and share it somewhere and get into trouble with steinborg.

**Comment by esaruoho** [comment] 2018-12-19 14:06
can the vs2017 configuration manager be used to build a 64-bit VST2 for Windows?

**Comment by getdunne** [comment] 2018-12-19 21:23
[surge-vst32proj.zip](https://github.com/kurasu/surge/files/2696528/surge-vst32proj.zip)
I don't have time to go through the pull-request process, but here is my .vcxproj for the VST2 build and instructions for how to use it, assuming you have access to the necessary files from the old VST2 SDK.

**Comment by jsakkine** [comment] 2018-12-22 06:44
Going through old issues for fun to find the dead leaves. Maybe you could try with a newer build? @kzantow was working on automatic Windows builds so maybe you could grab on of those. Dunno, what is the status of that effort, though.

**Comment by getdunne** [comment] 2018-12-22 14:08
I used the latest code pulled from GitHub, so this should be up to date. The only interesting aspect here is that there are a few patches which don’t work in 32-bit, and this may serve as a clue to where there might be a code problem such as questionable typedefs, casts, or struct definitions.

**Comment by kzantow** [comment] 2018-12-23 15:36
@getdunne maybe if you start compiling a list of problematic patches and post them here, it could help to diagnose things?

**Comment by esaruoho** [comment] 2018-12-29 09:16
@kzantow there's going to be problematic patches bugs posted at #181. this #14 seems to be a mixture of win32 compiling and then patch problems. better to list them there at #181

**Comment by esaruoho** [comment] 2018-12-29 10:35
@getdunne i'd recommend closing this ticket since the ASSYM bug manifests on 64-bit builds too and it is manifestly confusing to talk about win32 building working yet glitching if it is actually Surge-wide (32-bit, 64-bit). and, as noted and clarified in #181  - the issue is about `Waveshaper: ASSYM` mode and nothing to do with win32 builds.

**Closed** 2018-12-29 11:50 UTC

**Comment by esaruoho** [comment] 2019-01-03 15:06
let's see what that zip contains..

**Comment by esaruoho** [comment] 2019-01-03 15:10
@getdunne i took your attachment + writings + description and posted them to #97 - hopefully there'll be some benefit in them being mirrored there - because automated 32-bit windows builds would be loovely.

**Comment by getdunne** [comment] 2019-01-18 16:56
@esaruoho I got the latest code and can still build 64-bit VST2's (which work) and 32-bit VST2's, which fail, aways in the same spot: lipol.h line 84, called from lipol.h line 63, called from SurgeSuperOscillator.cpp line 64. Error is "Exception thrown.... Access violation reading location 0xFFFFFFFF".
